### ISSUE TITLE
Help implementing

### ISSUE THREAD

**Issue by justbane** [vapor-community/mailgun-provider#2]
Any help you can provide for implementing this?

**Comment by vzsg** [comment]
This package is obsolete.

Mailgun support is included in the parent project, see https://github.com/vapor/vapor/blob/master/Sources/Vapor/Mail/Mailgun.swift. It's unfortunately not documented much, but here's a quick walkthrough:

1. Create Config/mailgun.json with the following contents:
    ```
    {
        "domain": "your domain name",
        "key": "your API key"
    }
    ```
1. Change Config/droplet.json: `"mail": "mailgun"`.
1. Use the `drop.mail` whenever you want to send an email.

**Comment by justbane** [comment]
Good to know! Thanks for the reply, I'll give the included support a try.
